import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";
import AppSidebar from "@/components/navbar/app-sidebar";
import { Poppins } from "next/font/google";
import SessionProviderWrapper from "@/lib/sessionProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "To Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-svh ${poppins.className}`}>
        <SessionProviderWrapper>
          <SidebarProvider defaultOpen={true}>
            <AppSidebar />
            <main className="w-svw bg-zinc-200 relative">
              <SidebarTrigger className="absolute top-4 left-4" />
              {children}
            </main>
          </SidebarProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}