import ResponsiveLayout from "@/components/ResponsiveLayout";
import { ModeToggle } from "@/components/switchTheme";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import WrapperQueryClientProvider from "@/components/wrapperQueryProviders";
import SessionProviderWrapper from "@/lib/sessionProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "To Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`h-svh ${poppins.className}`}>
        <WrapperQueryClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProviderWrapper>
              <SidebarProvider defaultOpen={true}>
                <ResponsiveLayout>
                  <ModeToggle />
                  {children}
                </ResponsiveLayout>
              </SidebarProvider>
            </SessionProviderWrapper>
          </ThemeProvider>
        </WrapperQueryClientProvider>
      </body>
    </html>
  );
}
