import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";
import AppSidebar from "@/components/navbar/app-sidebar";
import { Poppins } from "next/font/google";
import SessionProviderWrapper from "@/lib/sessionProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/switchTheme";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "To Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`h-svh ${poppins.className}`}>
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProviderWrapper>
            <SidebarProvider defaultOpen={true}>
              <AppSidebar />
              <main className="w-svw relative">
                <ModeToggle />
                <SidebarTrigger className="absolute top-4 left-4" />
                {children}
              </main>
            </SidebarProvider>
          </SessionProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}